### PR TITLE
Moved 'use strict' declaration inside IIFE to avoid jshint warning

### PR DESCRIPTION
**Pull request by jrdrg**
I made a minor change to put 'use strict' inside the IIFE to avoid the "use function form of 'use strict'" warnings from jshint.

### CODE REVIEW

**Comment by yagoferrer** [comment]
Awesome! can you also make the change in spec/all.spec.js line 27 to fix the test?

**Comment by jrdrg** [comment]
Sure, done!

**Comment by yagoferrer** [comment]
Thanks!

**Comment by yagoferrer** [comment]
0.1.6 should have your fix! thanks again @jrdrg

**Comment by jrdrg** [comment]
Thanks!

**Pull request merged**
